### ISSUE TITLE
Missing ambient lighting in some of the 3d scene on macOS

### ISSUE THREAD

**Issue by bitinn** [gdquest-demos/godot-4-new-features#32]
Not sure this is a bug in Godot 4 itself as I have only found bug ticket related to 3.5.x;

https://github.com/godotengine/godot/issues/55754

But the behavior was the same, no ambient lighting results in complete black shadow in shaded area. Not all scenes are affected so I guess it's a certain type ambient lighting sources that are broken on macOS.

Will check the source project later.

broken:

<img width="960" alt="Screen Shot 2023-03-11 at 17 26 10" src="https://user-images.githubusercontent.com/1484279/224477276-b623c05f-95b2-45e8-b396-451b07434f56.png">

<img width="960" alt="Screen Shot 2023-03-11 at 17 26 33" src="https://user-images.githubusercontent.com/1484279/224477284-ee195963-f949-45f4-ba1c-e93ba7fc4e25.png">

working (as far as I can tell):

<img width="960" alt="Screen Shot 2023-03-11 at 17 42 50" src="https://user-images.githubusercontent.com/1484279/224477291-96f88e0f-834e-4129-8846-5be0a95a3c02.png">

<img width="960" alt="Screen Shot 2023-03-11 at 17 43 01" src="https://user-images.githubusercontent.com/1484279/224477299-7495f83a-7231-407b-824f-6c85a86c5a7c.png">

**Comment by NathanLovato** [comment]
Thanks for pointing this out, sorry for only getting to this now - I missed the notification. Closing as this is an engine-side issue.
